### ISSUE TITLE
Format City Budget spreadsheet

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/openbudgetwy#20]
Create the CSV file used to create the budget visualizations. Follow instructions provided here. https://github.com/citizenlabsgr/openbudgetwy/blob/master/CONTRIBUTING.md

**Comment by Allen616** [comment]
[Data files can be found here.](https://github.com/citizenlabsgr/openbudgetwy/tree/master/Data%20Files) Data is organized by year. Within every year I have created two directories within this for [Raw](https://github.com/citizenlabsgr/openbudgetwy/tree/master/Data%20Files/2018/Raw) (unprocessed file from City) and [Clean](https://github.com/citizenlabsgr/openbudgetwy/tree/master/Data%20Files/2018/Clean) (files that have been put into the correct format to create visualizations.

**Comment by Allen616** [comment]
Work on this has begun. We are still fine tuning how we organize the files. So things may move about  a bit while we work this out.

**Comment by Allen616** [comment]
Need Paul G to review the revised budget files for the [Flow](https://github.com/citizenlabsgr/openbudgetwy/tree/master/data-files/2019/flow) and [Drill down](https://github.com/citizenlabsgr/openbudgetwy/tree/master/data-files/2019/tree) visualizations.

**Comment by Allen616** [comment]
Thanks Paul. I have changed the header names and removed unnecessary columns. I just want to make sure I did this accurately.

**Comment by pgsmith-wyo** [comment]
I don't see any issues with the columns that you removed, although the lack of detail in the Flow sheet may make troubleshooting difficult due to the numerous duplicates (e.g. 2019,Public Works,101,Expense,Personal Services,1000).

The Flow sheet does have a misnamed column.  "amount" appears twice and it looks like the first occurrence should be "account category."

Also, I ran a quick check of the data against the original sheet and everything looks intact.  I know that was outside the scope of your request, but I was reviewing the sheets anyway.

**Comment by Allen616** [comment]
Thanks. I am going to move forward in creating the visuzalizations and then we can double check those to confirm.

**Comment by Allen616** [comment]
In creating the drill-down(tree) visualization I have came across missing budget data. The first example of this is in rows 535-592.

**Comment by pgsmith-wyo** [comment]
In many cases, revenues are not assigned to a department or division.  They are assigned to the general fund and then distributed from there.  Accordingly, the drill-down csv matches the original file that I submitted to you.

**Comment by Allen616** [comment]
Thanks Paul. Then I would imagine we should delete the rows that do not have specific dollar amounts. Thoughts?

**Comment by pgsmith-wyo** [comment]
If you're referring to the rows with zero values, I agree.  For the purposes of these visualizations, that should be fine.  There are a variety of reasons that an account would lack a non-zero dollar amount, but it's probably an unnecessary complication to find a way to display those values in the visualizations.  Unless you have plans to offer a multi-year comparison in the future or you expect some visitors will want to work with the csv for themselves, there's not a compelling reason to keep them.
