### ISSUE TITLE
Copy Checklist

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/openbudgetwy#3]
Create google sheet that identifies sections of site and copy needed. Also provide place for draft copy of each page.

**Comment by Allen616** [comment]
Link to the Google sheet for the site copy inventory. https://docs.google.com/spreadsheets/d/1c4n1OSBeBXzNr8gfTY1FCAMVPj35LfKkgTWyKW2yN1w/edit?usp=sharing

**Comment by Allen616** [comment]
Copy from the Grand Rapids version of site has been copied into the site copy inventory. Edits can be made in the Google sheet.

**Comment by Allen616** [comment]
After reviewing the site I think we can probably remove some of the pages to make the site simpler. Please also share if you would like to add something.

**Comment by JenStowell** [comment]
@Allen616  - I have updated the spreadsheet.  I just edited to insert the City of Wyoming where GR was placed.  I changed it to the FY2020, as I am thinking that is what we will be kicking off.  Not sure about the information listed for Citizen Lab (I am assuming that is something you update as needed).  As for adding pages, is this something we can do at a later time if needed? Take a look at it and let me know what you think.  Thanks.

**Comment by Allen616** [comment]
@JenStowell Thanks for updating the spreadsheet. We will move forward in updating content on the site, per the  spreadsheet. For the project team, you left GR contacts. I am guessing you will want Wyoming contacts. I will not include the GR contacts.

**Comment by JenStowell** [comment]
Yes, we will want Wyoming contacts.  Thank you.

**Comment by Allen616** [comment]
Removing Budget Process from website, awaiting Wyoming version. See [Issue #4](https://github.com/citizenlabsgr/openbudgetwy/issues/4)

**Comment by Allen616** [comment]
Content changes complete. Site can be clicking [Wyoming Open Budget](https://wybudget.citizenlabs.org)
