### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/openbudgetwy#6]

**Comment by Allen616** [comment]
We will add a Citizen Lab's google analytics and share. Does Wyoming also use Google Analytics? Would you like us to add Wyoming code so that you can also have direct access to analytics?

**Comment by PatFirestone** [comment]
We do use Google Analytics for our City Website.  Yes, it would be a good idea to have Analytics on this website.  I will forward the code once our website developer is back (he is on vacation this week).

**Comment by PatFirestone** [comment]
Attached file with our Google Analytics code.

[wyobudget-Google-Analytics.txt](https://github.com/citizenlabsgr/openbudgetwy/files/2626580/wyobudget-Google-Analytics.txt)

**Comment by Allen616** [comment]
Let me know if you are getting any data. I just added it to the site.

**Comment by Allen616** [comment]
Confirmed that site does include Wyoming's Google Analytics code. Have not heard confirmation from Wyoming. Will reopen if needed.
